version: "3.9"

services:
  db:
    image: postgres:15
    container_name: communes_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: communes
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: communes_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/communes
      PROJECT_NAME: interview_project
      SECRET_KEY: secret-key-here

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
